# Generated by Django 5.2.9 on 2025-12-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='product',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='products.product'),
            preserve_default=False,
        ),
    ]
