# Generated by Django 5.2.7 on 2025-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='subCat_banner_img/'),
        ),
    ]
